name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        cat requirements.txt | xargs -n 1 -L 1 $CONDA/bin/pip install install
        $CONDA/bin/pip install -e .
    - name: Test with pytest
      run: |
        py.test --cov=at2019dsg --nbval-lax --current-env
        coveralls
